# Generated by Django 5.0.2 on 2024-02-13 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_listing_owner_alter_listing_wardrobe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='wardrobe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='pages.wardrobe', verbose_name='listing'),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobbes', to=settings.AUTH_USER_MODEL, verbose_name='wardrobe'),
        ),
    ]
