# Generated by Django 5.0.2 on 2024-02-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_wardrobe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='is_for_sale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is for sale'),
        ),
    ]
